using System.Data;using System.Data.SqlClient;
namespace ClassLibrary.Datos;
public interface IRecuperacionContraseniaRepositorio{void Crear(int usuarioId,string tokenHash,DateTime expiracion,string origen);int? Validar(string tokenHash);bool ConsumirYCambiar(string tokenHash,string contraseniaHash);}
public class RecuperacionContraseniaRepositorio:IRecuperacionContraseniaRepositorio
{
 public void Crear(int usuarioId,string hash,DateTime exp,string origen){const string sql=@"UPDATE RecuperacionesContrasenia SET FechaUso=SYSUTCDATETIME() WHERE UsuarioId=@UsuarioId AND FechaUso IS NULL; INSERT INTO RecuperacionesContrasenia(UsuarioId,TokenHash,FechaExpiracion,SolicitadaDesde) VALUES(@UsuarioId,@Hash,@Expira,@Origen)";using var cn=Conexion.ObtenerConexion();using var c=new SqlCommand(sql,cn);c.Parameters.Add("@UsuarioId",SqlDbType.Int).Value=usuarioId;c.Parameters.Add("@Hash",SqlDbType.Char,64).Value=hash;c.Parameters.Add("@Expira",SqlDbType.DateTime2).Value=exp;c.Parameters.Add("@Origen",SqlDbType.NVarChar,64).Value=origen??"";cn.Open();c.ExecuteNonQuery();}
 public int? Validar(string hash){const string sql="SELECT UsuarioId FROM RecuperacionesContrasenia WHERE TokenHash=@Hash AND FechaUso IS NULL AND FechaExpiracion>SYSUTCDATETIME()";using var cn=Conexion.ObtenerConexion();using var c=new SqlCommand(sql,cn);c.Parameters.Add("@Hash",SqlDbType.Char,64).Value=hash;cn.Open();object? v=c.ExecuteScalar();return v==null?null:Convert.ToInt32(v);}
 public bool ConsumirYCambiar(string hash,string password){using var cn=Conexion.ObtenerConexion();cn.Open();using var tx=cn.BeginTransaction();const string buscar="SELECT UsuarioId FROM RecuperacionesContrasenia WITH(UPDLOCK,HOLDLOCK) WHERE TokenHash=@Hash AND FechaUso IS NULL AND FechaExpiracion>SYSUTCDATETIME()";using var q=new SqlCommand(buscar,cn,tx);q.Parameters.Add("@Hash",SqlDbType.Char,64).Value=hash;object? v=q.ExecuteScalar();if(v==null){tx.Rollback();return false;}int id=Convert.ToInt32(v);using var u=new SqlCommand("UPDATE Usuarios SET Contrasenia=@Password WHERE Id=@Id AND TipoDeUsuarioId<>2",cn,tx);u.Parameters.Add("@Password",SqlDbType.NVarChar,255).Value=password;u.Parameters.Add("@Id",SqlDbType.Int).Value=id;if(u.ExecuteNonQuery()!=1){tx.Rollback();return false;}using var t=new SqlCommand("UPDATE RecuperacionesContrasenia SET FechaUso=SYSUTCDATETIME() WHERE TokenHash=@Hash",cn,tx);t.Parameters.Add("@Hash",SqlDbType.Char,64).Value=hash;t.ExecuteNonQuery();tx.Commit();return true;}
}
