using ClassLibrary.Solicitudes;using System.Data;using System.Data.SqlClient;
namespace ClassLibrary.Datos;
public interface ISolicitudShaperRepositorio{int Crear(SolicitudShaper s);List<SolicitudShaper> Buscar(string busqueda,string estado);bool CambiarEstado(int id,string estado,string notas);}
public class SolicitudShaperRepositorio:ISolicitudShaperRepositorio
{
 public int Crear(SolicitudShaper s){const string sql=@"INSERT INTO SolicitudesShapers(Nombre,Email,Marca,Ubicacion,Celular,Instagram,AniosExperiencia,RealizaPersonalizadas,RealizaEnvios,Presentacion) OUTPUT INSERTED.Id VALUES(@Nombre,@Email,@Marca,@Ubicacion,@Celular,@Instagram,@Anios,@Personalizadas,@Envios,@Presentacion)";using var cn=Conexion.ObtenerConexion();using var c=new SqlCommand(sql,cn);c.Parameters.Add("@Nombre",SqlDbType.NVarChar,100).Value=s.Nombre;c.Parameters.Add("@Email",SqlDbType.NVarChar,150).Value=s.Email;c.Parameters.Add("@Marca",SqlDbType.NVarChar,150).Value=s.Marca;c.Parameters.Add("@Ubicacion",SqlDbType.NVarChar,120).Value=s.Ubicacion;c.Parameters.Add("@Celular",SqlDbType.NVarChar,40).Value=s.Celular;c.Parameters.Add("@Instagram",SqlDbType.NVarChar,100).Value=s.Instagram;c.Parameters.Add("@Anios",SqlDbType.Int).Value=s.AniosExperiencia;c.Parameters.Add("@Personalizadas",SqlDbType.Bit).Value=s.RealizaPersonalizadas;c.Parameters.Add("@Envios",SqlDbType.Bit).Value=s.RealizaEnvios;c.Parameters.Add("@Presentacion",SqlDbType.NVarChar,1500).Value=s.Presentacion;cn.Open();return Convert.ToInt32(c.ExecuteScalar());}
 public List<SolicitudShaper> Buscar(string b,string e){const string sql=@"SELECT * FROM SolicitudesShapers WHERE (@Busqueda='' OR Nombre LIKE '%'+@Busqueda+'%' OR Email LIKE '%'+@Busqueda+'%' OR Marca LIKE '%'+@Busqueda+'%') AND (@Estado='' OR Estado=@Estado) ORDER BY CASE Estado WHEN 'Pendiente' THEN 0 WHEN 'En revisión' THEN 1 ELSE 2 END,FechaCreacion DESC";using var cn=Conexion.ObtenerConexion();using var c=new SqlCommand(sql,cn);c.Parameters.Add("@Busqueda",SqlDbType.NVarChar,150).Value=b??"";c.Parameters.Add("@Estado",SqlDbType.NVarChar,30).Value=e??"";cn.Open();using var r=c.ExecuteReader();var l=new List<SolicitudShaper>();while(r.Read())l.Add(new(){Id=Convert.ToInt32(r["Id"]),Nombre=Convert.ToString(r["Nombre"])??"",Email=Convert.ToString(r["Email"])??"",Marca=Convert.ToString(r["Marca"])??"",Ubicacion=Convert.ToString(r["Ubicacion"])??"",Celular=Convert.ToString(r["Celular"])??"",Instagram=Convert.ToString(r["Instagram"])??"",AniosExperiencia=Convert.ToInt32(r["AniosExperiencia"]),RealizaPersonalizadas=Convert.ToBoolean(r["RealizaPersonalizadas"]),RealizaEnvios=Convert.ToBoolean(r["RealizaEnvios"]),Presentacion=Convert.ToString(r["Presentacion"])??"",Estado=Convert.ToString(r["Estado"])??"",NotasAdmin=Convert.ToString(r["NotasAdmin"])??"",FechaCreacion=Convert.ToDateTime(r["FechaCreacion"]),FechaActualizacion=r["FechaActualizacion"]==DBNull.Value?null:Convert.ToDateTime(r["FechaActualizacion"])});return l;}
 public bool CambiarEstado(int id,string estado,string notas){if(!new[]{"Pendiente","En revisión","Aprobada","Rechazada"}.Contains(estado))return false;const string sql="UPDATE SolicitudesShapers SET Estado=@Estado,NotasAdmin=@Notas,FechaActualizacion=SYSUTCDATETIME() WHERE Id=@Id";using var cn=Conexion.ObtenerConexion();using var c=new SqlCommand(sql,cn);c.Parameters.Add("@Id",SqlDbType.Int).Value=id;c.Parameters.Add("@Estado",SqlDbType.NVarChar,30).Value=estado;c.Parameters.Add("@Notas",SqlDbType.NVarChar,1000).Value=notas??"";cn.Open();return c.ExecuteNonQuery()==1;}
}
