using ClassLibrary.Datos;using System.Net;using System.Net.Mail;using System.Security.Cryptography;using System.Text;
namespace WebApplication2.Servicios;
public interface IRecuperacionContraseniaServicio{Task SolicitarAsync(string email,string enlaceBase,string origen);bool TokenValido(string token);bool Restablecer(string token,string nueva,string confirmar,out string error);}
public class RecuperacionContraseniaServicio(IUsuarioRepositorio usuarios,IRecuperacionContraseniaRepositorio tokens,IConfiguration config,ILogger<RecuperacionContraseniaServicio> logger,ICorreoNotificacionServicio correo):IRecuperacionContraseniaServicio
{
 public async Task SolicitarAsync(string email,string enlaceBase,string origen){var u=usuarios.ObtenerPorEmail((email??"").Trim());if(u==null||!u.Activo)return;byte[] bytes=RandomNumberGenerator.GetBytes(32);string token=Convert.ToHexString(bytes).ToLowerInvariant();tokens.Crear(u.Id,Hash(token),DateTime.UtcNow.AddMinutes(30),origen);string? cuenta=config["Correo:SmtpUsuario"],clave=config["Correo:SmtpContrasena"];if(string.IsNullOrWhiteSpace(cuenta)||string.IsNullOrWhiteSpace(clave)){logger.LogWarning("SMTP no configurado para recuperación de contraseña.");return;}string enlace=enlaceBase+(enlaceBase.Contains('?')?'&':'?')+"token="+Uri.EscapeDataString(token);using var m=new MailMessage{From=new MailAddress(cuenta,"Zephyr Surf Go"),Subject="Restablecé tu contraseña",IsBodyHtml=true,Body=$"<h2>Restablecer contraseña</h2><p>Recibimos una solicitud para tu cuenta.</p><p><a href=\"{WebUtility.HtmlEncode(enlace)}\">Crear una nueva contraseña</a></p><p>El enlace vence en 30 minutos y sólo puede utilizarse una vez. Si no fuiste vos, ignorá este correo.</p>"};m.To.Add(u.Email);try{using var smtp=new SmtpClient(config["Correo:SmtpHost"]??"smtp.gmail.com",config.GetValue("Correo:SmtpPuerto",587)){EnableSsl=true,Credentials=new NetworkCredential(cuenta,clave)};await smtp.SendMailAsync(m);}catch(Exception ex){logger.LogError(ex,"No se pudo enviar recuperación a {UsuarioId}",u.Id);}}
 public bool TokenValido(string token)=>!string.IsNullOrWhiteSpace(token)&&tokens.Validar(Hash(token))!=null;
 public bool Restablecer(string token,string nueva,string confirmar,out string error){if(nueva?.Length<8){error="La contraseña debe tener al menos 8 caracteres.";return false;}if(nueva!=confirmar){error="Las contraseñas no coinciden.";return false;}int? usuarioId=string.IsNullOrWhiteSpace(token)?null:tokens.Validar(Hash(token));if(usuarioId==null){error="El enlace venció o ya fue utilizado.";return false;}bool ok=tokens.ConsumirYCambiar(Hash(token),BCrypt.Net.BCrypt.HashPassword(nueva));if(ok)correo.EnviarAUsuarioAsync(usuarioId.Value,"Tu contraseña fue restablecida","Contraseña actualizada","La contraseña de tu cuenta fue restablecida mediante el enlace de recuperación. Si no fuiste vos, contactá al equipo.").GetAwaiter().GetResult();error=ok?"":"No pudimos actualizar la contraseña.";return ok;}
 private static string Hash(string token)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token??""))).ToLowerInvariant();
}
